// apps/playground/src/nodes/CoreNodeRenderer.vue
<script setup lang="ts">
import { computed } from "vue";
import type { FQueryUiEvent, NodeViewModel, PresentationProjection } from "@fquery/ui-core";
import PsiNlNode from "./PsiNlNode.vue";
import FamvimNode from "./FamvimNode.vue";
import LambdaNlNode from "./LambdaNlNode.vue";

/** rendererHint `fquery-core-node` に対する1つのrenderer。presentationId（presentation://fquery/core/<capability>）でCore 3 nodeを振り分ける。 */
const props = defineProps<{ model: NodeViewModel; projection?: PresentationProjection | undefined }>();
const emit = defineEmits<{ event: [event: FQueryUiEvent] }>();

const capability = computed(() => props.projection?.presentation?.presentationId ?? "");
const component = computed(() => {
  if (capability.value.includes("core.psi.nl-input")) return PsiNlNode;
  if (capability.value.includes("core.gradient.famvim")) return FamvimNode;
  if (capability.value.includes("core.lambda.nl-output")) return LambdaNlNode;
  return undefined;
});
</script>

<template>
  <component :is="component" v-if="component" :model="model" :projection="projection" @event="emit('event', $event)" />
  <p v-else class="fquery-canvas-node-muted">renderer未対応: {{ capability }}</p>
</template>

// apps/playground/src/nodes/CoreNodeRenderer.tsx
import type { NodeRendererProps } from "@fquery/ui-react";
import { PsiNlNode } from "./PsiNlNode.js";
import { FamvimNode } from "./FamvimNode.js";
import { LambdaNlNode } from "./LambdaNlNode.js";

/** rendererHint `fquery-core-node` に対する1つのrenderer。presentationIdでCore 3 nodeを振り分ける。 */
export function CoreNodeRenderer(props: NodeRendererProps) {
  const capability = props.projection?.presentation?.presentationId ?? "";
  if (capability.includes("core.psi.nl-input")) return <PsiNlNode {...props} />;
  if (capability.includes("core.gradient.famvim")) return <FamvimNode {...props} />;
  if (capability.includes("core.lambda.nl-output")) return <LambdaNlNode {...props} />;
  return <p className="fquery-canvas-node-muted">renderer未対応: {capability}</p>;
}
