// apps/playground/src/App.vue
<script setup lang="ts">
import { computed, onMounted, provide, ref, shallowRef, watch } from "vue";
import { FQueryBaklavaView, FQueryPane, type FQueryBaklavaViewHandle } from "@fquery/ui-vue";
import {
  PaneRegistry,
  PluginPresentationRegistry,
  PresentationSession,
  CORE_RENDERER_HINT,
  createPaneContext,
  corePortId,
  createCoreNodeViewModel,
  createFixtureDecisionPort,
  findCoreNodeContract,
  findRegistrationByPresentation,
  registerCoreNodes,
  statusTone,
  type FQueryUiEvent,
  type GuiEventAbi,
  type PresentationSessionState,
  type StatusBadgeViewModel,
} from "@fquery/ui-core";
import { isFamJsonRecord, readFamJson, validateFamJson } from "@fquery/fam-core";
import {
  FAM_DRAFT_PATCH_SCHEMA_VERSION,
  applyFamPatch,
  diffJson,
  escapeToken,
  getAtPointer,
  openFamText,
  parsePointer,
  patchFromDiff,
  serializeFamValue,
  type FamDraftPatch,
  type FamEditReceipt,
  type FamPatch,
  type JsonValue,
} from "@fquery/fam-edit";
import { decomposerContextKey, playgroundPaneContextKey, type PaneComponentMap, type PlaygroundEditReceiptView, type PlaygroundRoute } from "./context.js";
import CoreNodeRenderer from "./nodes/CoreNodeRenderer.vue";
import AddNodeSection from "./panes/AddNodeSection.vue";
import OutlinerSection from "./panes/OutlinerSection.vue";
import RecordsSection from "./panes/RecordsSection.vue";
import DecisionsSection from "./panes/DecisionsSection.vue";
import NodeSettingsSection from "./panes/NodeSettingsSection.vue";
import NodeConnectionsSection from "./panes/NodeConnectionsSection.vue";
import NodeQSection from "./panes/NodeQSection.vue";
import NodeUnsupportedSection from "./panes/NodeUnsupportedSection.vue";
import NodeRawSection from "./panes/NodeRawSection.vue";
import DecomposerSection from "./panes/DecomposerSection.vue";

type Route = PlaygroundRoute;

const routes = ref<readonly Route[]>([{ provider: "fixture", label: "Fixture", available: true, models: ["mock-fam-transformer"] }]);
const provider = ref<Route["provider"]>("fixture");
const model = ref("mock-fam-transformer");
const source = ref("雨が降っている。傘を持って出かける。ただし降水量は未確認である。");
const lastEvent = ref("未実行");
const response = ref<unknown>();
const running = ref(false);
const routeError = ref("");
const canvas = ref<FQueryBaklavaViewHandle>();
const leftOpen = ref(true);
const rightOpen = ref(false);
const inspectorTab = ref<"settings" | "connections" | "q" | "unsupported" | "raw" | undefined>();
const inspectorJump = ref<string | null>(null);
const rightTab = ref<string | undefined>();

// GUIは判定を行わない。Playgroundではengine不在のためfixture portが構造判定だけを返す。
const registry = new PluginPresentationRegistry();
registerCoreNodes(registry);
const session = new PresentationSession(createFixtureDecisionPort({
  registry,
  renderer: { rendererId: "vue-baklava", supportedHints: [CORE_RENDERER_HINT] },
  nodeIdPrefix: "q://playground/node",
  createNode: (capability, nodeId) => {
    const contract = findCoreNodeContract(capability);
    if (!contract) throw new Error(`core-contract-not-found:${capability}`);
    return createCoreNodeViewModel(contract, nodeId);
  },
  // Host責務: FAMVIM／Node Panelからのfam.patch / fam.textをcanonical valueへ適用する。GUIは適用しない。
  resolveProperty: (node, property, value, request) => {
    if (property !== "fam.patch" && property !== "fam.text") return undefined;
    if (node.value === null || node.value === undefined) return { rejected: "fam-not-provided" };
    let document;
    try {
      document = readFamJson(serializeFamValue(node.value as JsonValue));
    } catch (error) {
      return { rejected: error instanceof Error ? `canonical-fam-invalid:${error.message}` : "canonical-fam-invalid" };
    }

    let draftPatch: FamDraftPatch;
    if (property === "fam.patch") {
      draftPatch = value as FamDraftPatch;
      if (draftPatch.schemaVersion !== FAM_DRAFT_PATCH_SCHEMA_VERSION) return { rejected: "unsupported-draft-patch-schema-version" };
    } else {
      const draft = openFamText(String(value));
      if (draft.parse === "unparsed") return { rejected: `fam-text-unparsed:${draft.parseError}` };
      draftPatch = patchFromDiff(diffJson(document.value, draft.value));
    }

    let patches: readonly FamPatch[];
    try {
      patches = toEnginePatches(document.value, draftPatch);
    } catch (error) {
      return { rejected: error instanceof Error ? error.message : "draft-patch-adapter-failed" };
    }
    if (patches.length === 0) return node;

    editSequence += 1;
    const decision = applyFamPatch(document, {
      operationId: request.requestId,
      baseRevisionId: document.value.revision_id,
      resultRevisionId: `rev://playground/fam-edit/${editSequence}`,
      patches,
    }, { validate: validateFamJson });
    editReceiptRecords.value = [...editReceiptRecords.value, decision.receipt];
    if (decision.status === "rejected") return { rejected: decision.receipt.reason ?? "fam-edit-rejected" };
    const semantic = "unknown";
    return {
      ...node,
      value: decision.document.value,
      badges: [{ axis: "semantic", value: semantic, tone: statusTone(semantic) }],
      evidenceRefs: [...node.evidenceRefs, `fam-edit://${decision.receipt.operationId}/${decision.receipt.resultRevisionId}`],
    };
  },
}), { registry });
let editSequence = 0;
const editReceiptRecords = shallowRef<readonly FamEditReceipt[]>([]);
const editReceipts = computed<readonly PlaygroundEditReceiptView[]>(() => editReceiptRecords.value.map((receipt) => ({
  status: receipt.status,
  operationId: receipt.operationId,
  baseRevisionId: receipt.baseRevisionId,
  resultRevisionId: receipt.resultRevisionId,
  patchCount: receipt.patches.length,
  validationIssueCount: receipt.validationIssues.length,
  ...(receipt.reason ? { reason: receipt.reason } : {}),
  losses: receipt.losses,
  sourceMutation: receipt.sourceMutation,
  beforeSha256: receipt.beforeSha256,
  afterSha256: receipt.afterSha256,
})));
const sessionState = shallowRef<PresentationSessionState>(session.state);
session.subscribe((state) => { sessionState.value = state; });
const registrations = computed(() => session.registry.registrations());
const coreNodeIds = ref<{ psi?: string | undefined; famvim?: string | undefined; lambda?: string | undefined }>({});
let selectSequence = 0;

/** rendererHint -> canvas renderer。Core 3 nodeは最初のrenderer。pluginは同じ経路で自分のrendererを登録する。 */
const nodeRenderers = { [CORE_RENDERER_HINT]: CoreNodeRenderer };

provide(decomposerContextKey, { routes, provider, model, source, running, execute });

/**
 * pane contribution（Issue #33）。左=Tool（Add Node / Records / Decisions）、右=Inspector。
 * Coreのnode panelとHostのdecomposer sectionを同じregistryへ宣言し、pluginは
 * registration.editor.panesで同じ経路へ参加する。
 */
const paneRegistry = new PaneRegistry();
paneRegistry.register({ side: "left", tab: { id: "add", title: "Add Node", icon: "＋", order: 0 }, section: { id: "palette", title: "検索して追加", order: 0 }, componentRef: "host:add-node", source: "host" });
paneRegistry.register({ side: "left", tab: { id: "outline", title: "階層", icon: "☷", order: 10 }, section: { id: "outliner", title: "Nodes", order: 0 }, componentRef: "host:outliner", source: "host" });
paneRegistry.register({ side: "left", tab: { id: "records", title: "Records", icon: "▤", order: 20 }, section: { id: "records", title: "FAM / projection / FAMLog / receipt / debug", order: 0 }, componentRef: "host:records", source: "host" });
paneRegistry.register({ side: "left", tab: { id: "decisions", title: "Decisions", icon: "≡", order: 30 }, section: { id: "decisions", title: "Session decisions / FAM edit receipts", order: 0 }, componentRef: "host:decisions", source: "host" });
const withActive = (context: { activeNode?: unknown }) => context.activeNode !== undefined;
paneRegistry.register({ side: "right", tab: { id: "node", title: "Node", icon: "◈", order: 0 }, section: { id: "settings", title: "設定", order: 10 }, componentRef: "core:node-settings", source: "core", applies: withActive });
paneRegistry.register({ side: "right", tab: { id: "node", title: "Node", icon: "◈", order: 0 }, section: { id: "connections", title: "接続", order: 20 }, componentRef: "core:node-connections", source: "core", applies: withActive });
paneRegistry.register({ side: "right", tab: { id: "q", title: "Q", icon: "Q", order: 10 }, section: { id: "q-schema", title: "Q schema", order: 0 }, componentRef: "core:node-q", source: "core", applies: withActive });
paneRegistry.register({ side: "right", tab: { id: "unsupported", title: "Unsupported Data", icon: "?", order: 20 }, section: { id: "unsupported", title: "panel外のcanonical field", order: 0 }, componentRef: "core:node-unsupported", source: "core", applies: withActive });
paneRegistry.register({ side: "right", tab: { id: "raw", title: "RAW FAM", icon: "{}", order: 30 }, section: { id: "famvim", title: "∇φ.FAMVIM", order: 0, collapsible: false }, componentRef: "core:node-raw", source: "core", applies: withActive });
paneRegistry.register({ side: "right", tab: { id: "node", title: "Node", icon: "◈", order: 0 }, section: { id: "decomposer", title: "Ψ.NL decomposer route", order: 0 }, componentRef: "host:decomposer", source: "host", applies: (context) => context.famRole === "ψ" });
for (const registration of registry.registrations()) paneRegistry.registerPlugin(registration);
const paneComponents: PaneComponentMap = {
  "host:add-node": AddNodeSection,
  "host:outliner": OutlinerSection,
  "host:records": RecordsSection,
  "host:decisions": DecisionsSection,
  "core:node-settings": NodeSettingsSection,
  "core:node-connections": NodeConnectionsSection,
  "core:node-q": NodeQSection,
  "core:node-unsupported": NodeUnsupportedSection,
  "core:node-raw": NodeRawSection,
  "host:decomposer": DecomposerSection,
};

const selectedRoute = computed(() => routes.value.find((route) => route.provider === provider.value));
const resultRecord = computed<Record<string, unknown> | undefined>(() => {
  if (!isRecord(response.value) || !isRecord(response.value.result)) return undefined;
  return response.value.result;
});
const responseFam = computed(() => isFamJsonRecord(resultRecord.value?.value) ? resultRecord.value?.value : undefined);
const famvimNode = computed(() => sessionState.value.nodes.find((node) => node.nodeId === coreNodeIds.value.famvim));
/** canonical FAMは∇φ.FAMVIM nodeが保持するvalue。provider responseはその初期投影に過ぎない。 */
const fam = computed<unknown>(() => famvimNode.value?.value ?? undefined);
const psiNode = computed(() => sessionState.value.nodes.find((node) => node.nodeId === coreNodeIds.value.psi));
/** active cursor nodeはsessionのselection。未選択時はΨ.NLを既定にする */
const selectedNode = computed(() => sessionState.value.nodes.find((node) => node.nodeId === sessionState.value.selection.activeNodeId) ?? psiNode.value);
const selectedProjection = computed(() => selectedNode.value ? sessionState.value.presentations[selectedNode.value.nodeId] : undefined);
const selectedRegistration = computed(() => findRegistrationByPresentation(session.registry, selectedProjection.value?.presentation?.presentationId));
const paneContext = computed(() => createPaneContext({
  selection: selectedNode.value ? { nodeIds: sessionState.value.selection.nodeIds.length ? sessionState.value.selection.nodeIds : [selectedNode.value.nodeId], activeNodeId: selectedNode.value.nodeId } : sessionState.value.selection,
  nodes: sessionState.value.nodes,
  presentations: sessionState.value.presentations,
  registrations: registrations.value,
}));
const leftTabs = computed(() => paneRegistry.resolve("left", paneContext.value));
const rightTabs = computed(() => paneRegistry.resolve("right", paneContext.value));
const semanticProjection = computed(() => {
  const value = resultRecord.value?.value;
  return isRecord(value) && typeof value.schema_version === "string" && value.schema_version.startsWith("fquery.semantic-block-projection/") ? value : undefined;
});
const providerReceipt = computed(() => resultRecord.value ? {
  transport_status: resultRecord.value.transport_status,
  plugin_status: resultRecord.value.plugin_status,
  execution: resultRecord.value.execution,
  evidence_refs: resultRecord.value.evidence_refs,
} : undefined);
const debugEvents = computed(() => isRecord(response.value) && Array.isArray(response.value.events) ? response.value.events : undefined);

provide(playgroundPaneContextKey, { sessionState, registrations, fam, semanticProjection, providerReceipt, debugEvents, editReceipts, selectedRegistration, selectedProjection, inspectorTab, inspectorJump, validate: validateFamJson, receive });

/** Blender流: T=左Tool pane、N=右Inspector pane。入力中は無効。 */
function onKeydown(event: KeyboardEvent) {
  const target = event.target as HTMLElement | null;
  if (event.metaKey || event.ctrlKey || event.altKey) return;
  if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.tagName === "SELECT" || target.isContentEditable)) return;
  if (event.key === "t" || event.key === "T") { leftOpen.value = !leftOpen.value; event.preventDefault(); }
  if (event.key === "n" || event.key === "N") { rightOpen.value = !rightOpen.value; event.preventDefault(); }
  if (event.key === "Home") { frameAll(); event.preventDefault(); }
}

watch(provider, () => { model.value = selectedRoute.value?.models[0] ?? ""; response.value = undefined; routeError.value = ""; });
// Host責務: ∇φ.FAMVIMのcanonical FAMが変わったら、接続先λ.NLへmanifestationをfixture projectionとして投影する（λ判定はしない）
watch(fam, (value) => projectLambdaNode(value));

onMounted(async () => {
  await buildCoreGraph();
  try {
    const fetched = await fetch("/api/routes");
    if (!fetched.ok) throw new Error(`routes-http-${fetched.status}`);
    routes.value = await fetched.json() as readonly Route[];
  } catch (error) {
    routeError.value = error instanceof Error ? error.message : "route-discovery-failed";
  }
});

/** Core 3 nodeをpluginなしで構築する。接続の可否はportへ委譲する。 */
async function buildCoreGraph() {
  const psi = await addCoreNode("core.psi.nl-input", 1);
  const famvim = await addCoreNode("core.gradient.famvim", 2);
  const lambda = await addCoreNode("core.lambda.nl-output", 3);
  coreNodeIds.value = { psi, famvim, lambda };
  if (psi && famvim) await session.dispatch({ type: "connection.add.requested", requestId: "playground:connect:psi-famvim", fromPortId: corePortId(psi, "observation"), toPortId: corePortId(famvim, "psi") });
  if (famvim && lambda) await session.dispatch({ type: "connection.add.requested", requestId: "playground:connect:famvim-lambda", fromPortId: corePortId(famvim, "fam"), toPortId: corePortId(lambda, "fam") });
  const positions = [psi, famvim, lambda].map((nodeId, index) => ({ nodeId, x: 320 + index * 380, y: 120 }));
  for (const position of positions) {
    if (!position.nodeId) continue;
    await session.dispatch({ type: "node.move.requested", requestId: `playground:layout:${position.nodeId}`, nodeId: position.nodeId, layoutSlotRef: `layout://playground/${position.nodeId}`, x: position.x, y: position.y });
  }
}

async function addCoreNode(capability: string, sequence: number): Promise<string | undefined> {
  const state = await session.dispatch({ type: "node.add.requested", requestId: `playground:add:${sequence}`, capability });
  const decision = state.decisions.at(-1);
  return decision?.kind === "node.add" && decision.status === "accepted" ? decision.node?.nodeId : undefined;
}

function receive(event: FQueryUiEvent) {
  lastEvent.value = JSON.stringify(event);
  if (event.type === "focus") { canvas.value?.focusNode(event.nodeId); return; }
  if (event.type === "jump") {
    // Unsupported Data → RAW FAM。pane tabを切り替え、FAMVIMへpointerを渡す
    inspectorJump.value = event.pointer;
    rightTab.value = "raw";
    rightOpen.value = true;
    return;
  }
  if (event.type === "inspect") {
    selectSequence += 1;
    void session.dispatch({ type: "node.select.requested", requestId: `playground:select:${selectSequence}`, nodeIds: [event.nodeId], activeNodeId: event.nodeId });
    rightTab.value = event.nodeId === coreNodeIds.value.famvim ? "raw" : "node";
    rightOpen.value = true;
    return;
  }
  if (isGuiRequest(event)) {
    void session.dispatch(event).then((state) => {
      if (event.type === "node.add.requested") void placeUnplacedNodes(state);
    }).catch((error: unknown) => { routeError.value = error instanceof Error ? error.message : "session-dispatch-failed"; });
  }
}

let placementSequence = 0;
/**
 * Host責務: acceptされたlayoutが無いnodeをviewport中央へ置く。複数あれば縦へずらす。
 * 位置はPresentation FAMではなくlayout write-backとしてsessionへ通す。
 */
async function placeUnplacedNodes(state: PresentationSessionState) {
  const placed = new Set(state.layout.map((entry) => entry.nodeId));
  const unplaced = state.nodes.filter((node) => !placed.has(node.nodeId));
  if (unplaced.length === 0) return;
  const center = canvas.value?.viewportCenter() ?? { x: 400, y: 200 };
  for (const [index, node] of unplaced.entries()) {
    placementSequence += 1;
    await session.dispatch({
      type: "node.move.requested",
      requestId: `playground:place:${placementSequence}`,
      nodeId: node.nodeId,
      layoutSlotRef: `layout://playground/${node.nodeId}`,
      x: Math.round(center.x - 160),
      y: Math.round(center.y - 60 + index * 140),
    });
  }
}

function frameAll() { canvas.value?.zoomToFit(); }

async function execute() {
  running.value = true;
  response.value = undefined;
  routeError.value = "";
  projectPsiNode({ running: true });
  try {
    const fetched = await fetch("/api/decompose", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider: provider.value, model: model.value, source: source.value }) });
    const payload: unknown = await fetched.json();
    if (!fetched.ok) throw new Error(isRecord(payload) && typeof payload.error === "string" ? payload.error : `decompose-http-${fetched.status}`);
    response.value = payload;
    if (isRecord(payload) && Array.isArray(payload.events)) lastEvent.value = JSON.stringify(payload.events.at(-1) ?? "完了");
    projectPsiNode({ running: false });
    projectFamvimNode();
  } catch (error) {
    routeError.value = error instanceof Error ? error.message : "decompose-failed";
    projectPsiNode({ running: false });
  } finally {
    running.value = false;
  }
}

/** engineが返したQueryResultをΨ.NL nodeへ投影する。GUIはstatusを再計算しない。 */
function projectPsiNode(options: { running: boolean }) {
  const node = psiNode.value;
  if (!node) return;
  const record = resultRecord.value;
  const badges: StatusBadgeViewModel[] = (["resolution", "connection", "transport", "plugin", "semantic", "lambda", "control"] as const).map((axis) => {
    const raw = record?.[`${axis}_status`];
    const value = options.running && axis === "plugin" ? "running" : typeof raw === "string" ? raw : axis === "semantic" || axis === "lambda" ? "unknown" : "not-requested";
    return { axis, value, tone: statusTone(value) };
  });
  session.applyEngineEvent({ type: "fam.node.changed", node: { ...node, badges, value: { source_text: source.value, provider: provider.value, model: model.value }, canExecute: false } });
}

/** 分解結果FAMを∇φ.FAMVIM nodeのvalueへ投影する。正本はこのnodeのvalueであり、records paneは複製表示。 */
function projectFamvimNode() {
  const node = famvimNode.value;
  if (!node) return;
  const semantic = responseFam.value ? "unknown" : "not-evaluated";
  session.applyEngineEvent({ type: "fam.node.changed", node: { ...node, badges: [{ axis: "semantic", value: semantic, tone: statusTone(semantic) }], value: responseFam.value ?? null } });
}

/** λ.NLへmanifestationを投影する。fixture projectionであり、λ satisfactionは`unknown`のまま。 */
function projectLambdaNode(value: unknown) {
  const nodeId = coreNodeIds.value.lambda;
  const node = nodeId ? sessionState.value.nodes.find((entry) => entry.nodeId === nodeId) : undefined;
  if (!node) return;
  const connected = sessionState.value.connections.some((connection) => connection.toPortId === corePortId(node.nodeId, "fam"));
  const lambda = isRecord(value) && isRecord(value.λ) ? value.λ : undefined;
  const units = lambda && Array.isArray(lambda.output_units) ? lambda.output_units : [];
  const manifestations = units.map((unit) => isRecord(unit) && isRecord(unit.λ) && typeof unit.λ.manifestation === "string" ? unit.λ.manifestation : "").filter(Boolean);
  const projected = connected && manifestations.length > 0;
  session.applyEngineEvent({
    type: "fam.node.changed",
    node: {
      ...node,
      badges: [{ axis: "lambda", value: "unknown", tone: statusTone("unknown") }],
      value: projected ? { projection_kind: "fixture-projection", manifestations } : null,
    },
  });
}

/**
 * GUIのlossless draft patchをCore engineのoperationへ写像する。
 * object fieldのinsertはCoreのset（新規keyを許可）へ、array要素のinsertは
 * 親array path + indexへ変換する。採否とrevision更新はCoreだけが行う。
 */
function toEnginePatches(sourceValue: JsonValue, draft: FamDraftPatch): readonly FamPatch[] {
  return Object.freeze(draft.operations.map((operation): FamPatch => {
    if (operation.op !== "insert") return operation;
    const tokens = parsePointer(operation.path);
    if (tokens.length === 0) return { op: "set", path: "", value: operation.value };
    const finalToken = tokens[tokens.length - 1]!;
    const parentPath = tokens.length === 1
      ? ""
      : `/${tokens.slice(0, -1).map(escapeToken).join("/")}`;
    const parent = getAtPointer(sourceValue, parentPath);
    if (!Array.isArray(parent)) return { op: "set", path: operation.path, value: operation.value };
    const index = finalToken === "-" ? parent.length : Number(finalToken);
    if (!Number.isSafeInteger(index) || index < 0) throw new TypeError(`draft-array-index-invalid:${finalToken}`);
    return { op: "insert", path: parentPath, index, value: operation.value };
  }));
}

function isGuiRequest(event: FQueryUiEvent): event is GuiEventAbi {
  return event.type.endsWith(".requested") || event.type.startsWith("plugin.presentation.");
}

function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null; }
</script>

<template>
  <div class="shell" tabindex="-1" @keydown="onKeydown">
    <header class="topbar">
      <button type="button" class="hamburger" :aria-pressed="leftOpen ? 'true' : 'false'" aria-label="toggle tool pane (T)" title="Tool pane (T)" @click="leftOpen = !leftOpen">☰</button>
      <div>
        <p class="eyebrow">FQUERY NODE EDITOR</p>
        <h1>FQuery Playground — Ψ.NL → ∇φ.FAMVIM → λ.NL</h1>
      </div>
      <output aria-live="polite">last event: {{ lastEvent }}</output>
      <span class="spacer" />
      <p v-if="routeError" class="error" role="alert">{{ routeError }}</p>
      <button type="button" title="Frame all (Home)" @click="frameAll">Frame all</button>
      <button type="button" class="hamburger" :aria-pressed="rightOpen ? 'true' : 'false'" aria-label="toggle inspector pane (N)" title="Inspector pane (N)" @click="rightOpen = !rightOpen">☰</button>
    </header>

    <main class="stage" aria-label="node editor">
      <FQueryPane v-model:open="leftOpen" class="overlay-left" side="left" storage-key="fquery.playground" :tabs="leftTabs" :components="paneComponents" :context="paneContext" @event="receive" />
      <FQueryBaklavaView
        ref="canvas"
        fill
        :nodes="sessionState.nodes"
        :connections="sessionState.connections"
        :layout="sessionState.layout"
        :presentations="sessionState.presentations"
        :node-renderers="nodeRenderers"
        :selection="sessionState.selection"
        @event="receive"
      />
      <FQueryPane v-model:open="rightOpen" v-model:active-tab="rightTab" class="overlay-right" side="right" storage-key="fquery.playground" :tabs="rightTabs" :components="paneComponents" :context="paneContext" @event="receive" />
    </main>
  </div>
</template>

// apps/playground-react/src/App.tsx
import { useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent } from "react";
import { FQueryFlowView, FQueryPane, type NodeRendererMap, type PresentationCanvasHandle } from "@fquery/ui-react";
import { CORE_RENDERER_HINT, createPaneContext, findRegistrationByPresentation, type FQueryUiEvent, type GuiEventAbi } from "@fquery/ui-core";
import { validateFamJson } from "@fquery/fam-core";
import { createPlaygroundSession } from "./host/session.js";
import { useEditReceipts, useSessionState } from "./host/use-session.js";
import { buildCoreGraph, placeUnplacedNodes, type CoreNodeIds } from "./host/core-graph.js";
import { DecomposerContext, FIXTURE_ROUTE, isRecord, projectFamvimNode, projectLambdaNode, projectPsiNode, requestDecompose, resultRecord, type DecomposerContextValue, type PlaygroundRoute } from "./host/decomposer.js";
import { PANE_COMPONENTS, createPlaygroundPaneRegistry } from "./host/pane-registry.js";
import { PlaygroundPaneContext, type PlaygroundEditReceiptView, type PlaygroundPaneContextValue } from "./context.js";
import { CoreNodeRenderer } from "./nodes/CoreNodeRenderer.js";

/** rendererHint -> canvas renderer。Core 3 nodeは最初のrenderer。pluginは同じ経路で登録する。 */
const NODE_RENDERERS: NodeRendererMap = { [CORE_RENDERER_HINT]: CoreNodeRenderer };

/**
 * Playground（React）。composition rootであり、domain logicは`host/`へ置く。
 * canonical stateはsessionが持ち、React stateにはUI局所状態だけを置く。
 */
export function App() {
  const { session, receipts } = useMemo(() => createPlaygroundSession(), []);
  const paneRegistry = useMemo(() => createPlaygroundPaneRegistry(session.registry), [session]);
  const state = useSessionState(session);
  const editReceiptRecords = useEditReceipts(receipts);
  const canvas = useRef<PresentationCanvasHandle>(null);
  const coreIds = useRef<CoreNodeIds>({});
  // dev modeのStrictMode二重effectとFast Refreshのeffect再実行でCore graphを二重構築しないための同期guard
  const coreGraphBuilt = useRef(false);
  const [routes, setRoutes] = useState<readonly PlaygroundRoute[]>([FIXTURE_ROUTE]);
  const [provider, setProvider] = useState<PlaygroundRoute["provider"]>("fixture");
  const [model, setModel] = useState(FIXTURE_ROUTE.models[0] ?? "");
  const [source, setSource] = useState("雨が降っている。傘を持って出かける。ただし降水量は未確認である。");
  const [running, setRunning] = useState(false);
  const [response, setResponse] = useState<unknown>();
  const [lastEvent, setLastEvent] = useState("未実行");
  const [error, setError] = useState("");
  const [leftOpen, setLeftOpen] = useState(true);
  const [rightOpen, setRightOpen] = useState(false);
  const [rightTab, setRightTab] = useState<string | undefined>();
  const [inspectorJump, setInspectorJump] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    if (!coreGraphBuilt.current) {
      coreGraphBuilt.current = true;
      void buildCoreGraph(session).then((ids) => { coreIds.current = ids; });
    }
    void fetch("/api/routes")
      .then(async (fetched) => { if (!fetched.ok) throw new Error(`routes-http-${fetched.status}`); return await fetched.json() as readonly PlaygroundRoute[]; })
      .then((fetchedRoutes) => { if (!cancelled) setRoutes(fetchedRoutes); })
      .catch((reason: unknown) => { if (!cancelled) setError(reason instanceof Error ? reason.message : "route-discovery-failed"); });
    return () => { cancelled = true; };
  }, [session]);

  const receive = useCallback((event: FQueryUiEvent) => {
    setLastEvent(JSON.stringify(event));
    if (event.type === "focus") { canvas.current?.focusNode(event.nodeId); return; }
    if (event.type === "jump") {
      // Unsupported Data → RAW FAM。pane tabを切り替え、FAMVIMへpointerを渡す
      setInspectorJump(event.pointer);
      setRightTab("raw");
      setRightOpen(true);
      return;
    }
    if (event.type === "inspect") {
      void session.dispatch({ type: "node.select.requested", requestId: `playground:select:${Date.now()}`, nodeIds: [event.nodeId], activeNodeId: event.nodeId });
      setRightTab(event.nodeId === coreIds.current.famvim ? "raw" : "node");
      setRightOpen(true);
      return;
    }
    if (!isGuiRequest(event)) return;
    void session.dispatch(event).then((next) => {
      if (event.type === "node.add.requested") return placeUnplacedNodes(session, next, canvas.current?.viewportCenter() ?? { x: 400, y: 200 });
      return undefined;
    }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "session-dispatch-failed"));
  }, [session]);

  const execute = useCallback(async () => {
    setRunning(true);
    setError("");
    setResponse(undefined);
    projectPsiNode(session, coreIds.current, { response: undefined, running: true, source, provider, model });
    const outcome = await requestDecompose({ provider, model, source });
    if (outcome.error) setError(outcome.error);
    setResponse(outcome.response);
    if (isRecord(outcome.response) && Array.isArray(outcome.response.events)) setLastEvent(JSON.stringify(outcome.response.events.at(-1) ?? "完了"));
    projectPsiNode(session, coreIds.current, { response: outcome.response, running: false, source, provider, model });
    projectFamvimNode(session, coreIds.current, outcome.response);
    projectLambdaNode(session, coreIds.current);
    setRunning(false);
  }, [session, source, provider, model]);

  const decomposer = useMemo<DecomposerContextValue>(() => ({
    routes, provider, model, source, running,
    setProvider: (next) => { setProvider(next); setModel(routes.find((route) => route.provider === next)?.models[0] ?? ""); setResponse(undefined); setError(""); },
    setModel, setSource, execute,
  }), [routes, provider, model, source, running, execute]);

  // Host責務: ∇φ.FAMVIMのcanonical FAMが変わったら、接続先λ.NLへmanifestationをfixture projectionとして投影する（λ判定はしない）
  const famvimNode = state.nodes.find((node) => node.nodeId === coreIds.current.famvim);
  const fam = famvimNode?.value ?? undefined;
  useEffect(() => { projectLambdaNode(session, coreIds.current); }, [session, fam]);

  const psiNode = state.nodes.find((node) => node.nodeId === coreIds.current.psi);
  /** active cursor nodeはsessionのselection。未選択時はΨ.NLを既定にする */
  const selectedNode = state.nodes.find((node) => node.nodeId === state.selection.activeNodeId) ?? psiNode;
  const selectedProjection = selectedNode ? state.presentations[selectedNode.nodeId] : undefined;
  const registrations = session.registry.registrations();
  const selectedRegistration = findRegistrationByPresentation(session.registry, selectedProjection?.presentation?.presentationId);
  const paneContext = useMemo(() => createPaneContext({
    selection: selectedNode ? { nodeIds: state.selection.nodeIds.length ? state.selection.nodeIds : [selectedNode.nodeId], activeNodeId: selectedNode.nodeId } : state.selection,
    nodes: state.nodes,
    presentations: state.presentations,
    registrations,
  }), [state, selectedNode, registrations]);
  const leftTabs = useMemo(() => paneRegistry.resolve("left", paneContext), [paneRegistry, paneContext]);
  const rightTabs = useMemo(() => paneRegistry.resolve("right", paneContext), [paneRegistry, paneContext]);

  const record = resultRecord(response);
  const semanticProjection = isRecord(record?.value) && typeof record.value.schema_version === "string" && record.value.schema_version.startsWith("fquery.semantic-block-projection/") ? record.value : undefined;
  const providerReceipt = record ? { transport_status: record.transport_status, plugin_status: record.plugin_status, execution: record.execution, evidence_refs: record.evidence_refs } : undefined;
  const debugEvents = isRecord(response) && Array.isArray(response.events) ? response.events : undefined;
  const editReceipts = useMemo<readonly PlaygroundEditReceiptView[]>(() => editReceiptRecords.map((receipt) => ({
    status: receipt.status,
    operationId: receipt.operationId,
    baseRevisionId: receipt.baseRevisionId,
    resultRevisionId: receipt.resultRevisionId,
    patchCount: receipt.patches.length,
    validationIssueCount: receipt.validationIssues.length,
    ...(receipt.reason ? { reason: receipt.reason } : {}),
    losses: receipt.losses,
    sourceMutation: receipt.sourceMutation,
    beforeSha256: receipt.beforeSha256,
    afterSha256: receipt.afterSha256,
  })), [editReceiptRecords]);

  const paneHost = useMemo<PlaygroundPaneContextValue>(() => ({
    sessionState: state, registrations, fam, semanticProjection, providerReceipt, debugEvents, editReceipts,
    selectedRegistration, selectedProjection, inspectorJump, validate: validateFamJson, receive,
  }), [state, registrations, fam, semanticProjection, providerReceipt, debugEvents, editReceipts, selectedRegistration, selectedProjection, inspectorJump, receive]);

  /** Blender流: T=左Tool pane、N=右Inspector pane、Home=Frame all。入力中は無効。 */
  function onKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    const target = event.target as HTMLElement | null;
    if (event.metaKey || event.ctrlKey || event.altKey) return;
    if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.tagName === "SELECT" || target.isContentEditable)) return;
    if (event.key === "t" || event.key === "T") { setLeftOpen((open) => !open); event.preventDefault(); }
    if (event.key === "n" || event.key === "N") { setRightOpen((open) => !open); event.preventDefault(); }
    if (event.key === "Home") { canvas.current?.zoomToFit(); event.preventDefault(); }
  }

  return (
    <DecomposerContext.Provider value={decomposer}>
      <PlaygroundPaneContext.Provider value={paneHost}>
        <div className="shell" tabIndex={-1} onKeyDown={onKeyDown}>
          <header className="topbar">
            <button type="button" className="hamburger" aria-pressed={leftOpen} aria-label="toggle tool pane (T)" title="Tool pane (T)" onClick={() => setLeftOpen((open) => !open)}>☰</button>
            <div>
              <p className="eyebrow">FQUERY NODE EDITOR · REACT FLOW</p>
              <h1>FQuery Playground (React) — Ψ.NL → ∇φ.FAMVIM → λ.NL</h1>
            </div>
            <output aria-live="polite">last event: {lastEvent}</output>
            <span className="spacer" />
            {error && <p className="error" role="alert">{error}</p>}
            <button type="button" title="Frame all (Home)" onClick={() => canvas.current?.zoomToFit()}>Frame all</button>
            <button type="button" className="hamburger" aria-pressed={rightOpen} aria-label="toggle inspector pane (N)" title="Inspector pane (N)" onClick={() => setRightOpen((open) => !open)}>☰</button>
          </header>
          <main className="stage" aria-label="node editor">
            <div className="overlay-left">
              <FQueryPane side="left" storageKey="fquery.playground-react" tabs={leftTabs} components={PANE_COMPONENTS} context={paneContext} open={leftOpen} onEvent={receive} onOpenChange={setLeftOpen} />
            </div>
            <FQueryFlowView
              ref={canvas}
              nodes={state.nodes}
              connections={state.connections}
              layout={state.layout}
              decisions={state.decisions}
              presentations={state.presentations}
              nodeRenderers={NODE_RENDERERS}
              selection={state.selection}
              onEvent={receive}
              requestPrefix="ui"
            />
            <div className="overlay-right">
              <FQueryPane side="right" storageKey="fquery.playground-react" tabs={rightTabs} components={PANE_COMPONENTS} context={paneContext} open={rightOpen} activeTab={rightTab} onEvent={receive} onOpenChange={setRightOpen} onActiveTabChange={setRightTab} />
            </div>
          </main>
        </div>
      </PlaygroundPaneContext.Provider>
    </DecomposerContext.Provider>
  );
}

function isGuiRequest(event: FQueryUiEvent): event is GuiEventAbi {
  return event.type.endsWith(".requested") || event.type.startsWith("plugin.presentation.");
}
